### PR TITLE
Implemented Result class

### PR DESCRIPTION
**Pull request by ktran0918**
Members representing game's result, a square, and a ship are added. Getter and setter functions for these members are also implemented.

### CODE REVIEW

**Comment by barnesjt** [comment]
Hey couple of things: setLocation needs to refer to location and getResults returns the incorrect thing. Please fix, thanks.

**Review by barnesjt — CHANGES_REQUESTED** [review]
Please fix getResult() and SetLocation(Square)

**Review by barnesjt — APPROVED** [review]
Good to go.

**Comment by ngorog** [comment]
Result class looks good, the accessors and setters look simple and well done.

**Pull request merged**
